# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import my_service_pb2 as my__service__pb2


class RemoteControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteCommand = channel.unary_unary(
                '/remotecontrol.RemoteControl/ExecuteCommand',
                request_serializer=my__service__pb2.CommandRequest.SerializeToString,
                response_deserializer=my__service__pb2.CommandResponse.FromString,
                )


class RemoteControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=my__service__pb2.CommandRequest.FromString,
                    response_serializer=my__service__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'remotecontrol.RemoteControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RemoteControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/remotecontrol.RemoteControl/ExecuteCommand',
            my__service__pb2.CommandRequest.SerializeToString,
            my__service__pb2.CommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
